"use node";

import { action } from "./_generated/server";
import { v } from "convex/values";
import { internal } from "./_generated/api";

/**
 * AI-POWERED NICHE DISCOVERY
 * Uses real AI (Groq) to discover and analyze trending niches
 * NO FAKE OR MOCK DATA - All niches generated by AI
 */

interface NicheAnalysis {
  title: string;
  description: string;
  category: string;
  trendScore: number;
  searchVolume: number;
  competitionLevel: "Low" | "Medium" | "High";
  keywords: string[];
  reasoning: string;
}

/**
 * Discover trending niches using AI
 * Uses Groq (Fast LLM) to analyze trends and generate niche ideas
 */
export const discoverTrendingNiches = action({
  args: {
    category: v.optional(v.string()),
    count: v.optional(v.number()),
  },
  handler: async (ctx, args): Promise<NicheAnalysis[]> => {
    const groqKey = process.env.GROQ_API_KEY;

    if (!groqKey) {
      throw new Error("GROQ_API_KEY not configured. Cannot discover niches.");
    }

    const category = args.category || "all";
    const count = args.count || 10;

    try {
      // Use Groq AI to discover trending niches
      const prompt = category === "all"
        ? `You are a YouTube niche discovery expert. Analyze current trends and discover ${count} highly profitable YouTube niche ideas across various categories.

For each niche, provide:
1. Title (catchy and specific)
2. Description (1-2 sentences explaining the niche)
3. Category (Gaming, Education, Tech, Lifestyle, Finance, Entertainment, DIY, Health, etc.)
4. Trend Score (1-100, based on current trending topics and search interest)
5. Estimated Monthly Search Volume (realistic number between 10000-5000000)
6. Competition Level (Low/Medium/High based on market saturation)
7. 5 relevant keywords
8. Brief reasoning why this niche is trending

Focus on:
- Current viral trends and topics
- Emerging technologies (AI, Web3, etc.)
- Evergreen profitable niches
- Underserved audiences
- High engagement potential

Return ONLY valid JSON array with this exact structure:
[{
  "title": "string",
  "description": "string",
  "category": "string",
  "trendScore": number,
  "searchVolume": number,
  "competitionLevel": "Low" | "Medium" | "High",
  "keywords": ["string"],
  "reasoning": "string"
}]`
        : `You are a YouTube niche discovery expert. Discover ${count} highly profitable YouTube niche ideas specifically in the ${category} category.

For each niche, provide:
1. Title (catchy and specific to ${category})
2. Description (1-2 sentences explaining the niche)
3. Category (must be "${category}")
4. Trend Score (1-100, based on current trending topics in ${category})
5. Estimated Monthly Search Volume (realistic number between 10000-5000000)
6. Competition Level (Low/Medium/High based on ${category} market saturation)
7. 5 relevant keywords
8. Brief reasoning why this ${category} niche is trending

Focus on:
- Current ${category} viral trends
- Emerging sub-niches in ${category}
- Underserved ${category} audiences
- High ${category} engagement potential

Return ONLY valid JSON array with this exact structure:
[{
  "title": "string",
  "description": "string",
  "category": "${category}",
  "trendScore": number,
  "searchVolume": number,
  "competitionLevel": "Low" | "Medium" | "High",
  "keywords": ["string"],
  "reasoning": "string"
}]`;

      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${groqKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            {
              role: "system",
              content: "You are a YouTube niche discovery AI. Return ONLY valid JSON arrays, no markdown, no explanations."
            },
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.8,
          max_tokens: 4000,
          response_format: { type: "json_object" }
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Groq API error ${response.status}: ${errorText}`);
      }

      const data = await response.json();
      const content = data.choices[0]?.message?.content;

      if (!content) {
        throw new Error("No content from Groq AI");
      }

      // Parse AI response
      let niches: NicheAnalysis[];
      try {
        // Try parsing as JSON object first (with array property)
        const parsed = JSON.parse(content);
        niches = Array.isArray(parsed) ? parsed : (parsed.niches || Object.values(parsed)[0]);
      } catch {
        // If that fails, try to extract JSON array from text
        const jsonMatch = content.match(/\[[\s\S]*\]/);
        if (!jsonMatch) {
          throw new Error("Could not extract JSON from AI response");
        }
        niches = JSON.parse(jsonMatch[0]);
      }

      // Validate and clean niches
      const validNiches = niches
        .filter(n => n.title && n.description && n.category)
        .slice(0, count)
        .map(n => ({
          title: n.title,
          description: n.description,
          category: n.category,
          trendScore: Math.min(100, Math.max(1, n.trendScore || 50)),
          searchVolume: Math.min(5000000, Math.max(10000, n.searchVolume || 100000)),
          competitionLevel: (n.competitionLevel || "Medium") as "Low" | "Medium" | "High",
          keywords: Array.isArray(n.keywords) ? n.keywords.slice(0, 5) : [],
          reasoning: n.reasoning || ""
        }));

      // Store niches in database
      for (const niche of validNiches) {
        await ctx.runMutation(internal.youtubeQueries.storeNiche, {
          title: niche.title,
          description: niche.description,
          category: niche.category,
          trendScore: niche.trendScore,
          searchVolume: niche.searchVolume,
          competitionLevel: niche.competitionLevel,
          keywords: niche.keywords,
        });
      }

      console.log(`✅ Discovered ${validNiches.length} real AI-powered niches`);

      return validNiches;

    } catch (error: any) {
      console.error("Niche discovery error:", error);
      throw new Error(`Failed to discover niches: ${error.message}`);
    }
  },
});

/**
 * Analyze a specific niche idea with AI
 * Get detailed analysis and recommendations
 */
export const analyzeNiche = action({
  args: {
    nicheIdea: v.string(),
  },
  handler: async (ctx, args): Promise<{
    analysis: string;
    opportunities: string[];
    challenges: string[];
    contentIdeas: string[];
    monetizationStrategies: string[];
  }> => {
    const groqKey = process.env.GROQ_API_KEY;

    if (!groqKey) {
      throw new Error("GROQ_API_KEY not configured");
    }

    try {
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${groqKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            {
              role: "system",
              content: "You are a YouTube niche analysis expert. Provide detailed, actionable analysis in JSON format."
            },
            {
              role: "user",
              content: `Analyze this YouTube niche idea: "${args.nicheIdea}"

Provide:
1. Overall analysis (2-3 paragraphs)
2. 5 key opportunities
3. 5 main challenges
4. 10 specific content ideas
5. 5 monetization strategies

Return ONLY valid JSON:
{
  "analysis": "string",
  "opportunities": ["string"],
  "challenges": ["string"],
  "contentIdeas": ["string"],
  "monetizationStrategies": ["string"]
}`
            }
          ],
          temperature: 0.7,
          max_tokens: 2000,
        }),
      });

      if (!response.ok) {
        throw new Error(`Groq API error: ${response.status}`);
      }

      const data = await response.json();
      const content = data.choices[0]?.message?.content;

      if (!content) {
        throw new Error("No analysis from AI");
      }

      // Parse response
      try {
        const parsed = JSON.parse(content);
        return {
          analysis: parsed.analysis || "Analysis not available",
          opportunities: Array.isArray(parsed.opportunities) ? parsed.opportunities : [],
          challenges: Array.isArray(parsed.challenges) ? parsed.challenges : [],
          contentIdeas: Array.isArray(parsed.contentIdeas) ? parsed.contentIdeas : [],
          monetizationStrategies: Array.isArray(parsed.monetizationStrategies) ? parsed.monetizationStrategies : [],
        };
      } catch {
        return {
          analysis: content,
          opportunities: [],
          challenges: [],
          contentIdeas: [],
          monetizationStrategies: [],
        };
      }

    } catch (error: any) {
      console.error("Niche analysis error:", error);
      throw new Error(`Failed to analyze niche: ${error.message}`);
    }
  },
});
